// client/src/components/payment/PaymentDialog.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'

type PaymentStep = 'select' | 'processing' | 'success'
type PaymentMethod = 'qr' | 'card' | 'mobile'

const props = defineProps<{
  open: boolean
  courseTitle: string
  price: string
  isSubmitting: boolean
}>()

const emit = defineEmits<{
  close: []
  success: [method: PaymentMethod]
}>()

const step = ref<PaymentStep>('select')
const selectedMethod = ref<PaymentMethod>('qr')

const methods: { id: PaymentMethod; label: string; desc: string; icon: string }[] = [
  { id: 'qr', label: 'QR Code', desc: 'ສະແກນ QR ເພື່ອຊຳລະ', icon: '▦' },
  { id: 'card', label: 'Card', desc: 'Visa / Mastercard', icon: '▭' },
  { id: 'mobile', label: 'Mobile Banking', desc: 'BCEL One, JDB, LDB', icon: '▣' },
]

const numericPrice = computed(() => {
  const amount = Number(String(props.price || 0).replace(/,/g, ''))
  return Number.isNaN(amount) ? 0 : amount
})

const commission = computed(() => Math.round(numericPrice.value * 0.2))
const teacherEarning = computed(() => numericPrice.value - commission.value)

const formatMoney = (amount: number) => {
  return `₭${amount.toLocaleString('en-US')}`
}

const handlePay = (method: PaymentMethod) => {
  selectedMethod.value = method
  step.value = 'processing'

  window.setTimeout(() => {
    step.value = 'success'
  }, 900)
}

const handleSuccess = () => {
  emit('success', selectedMethod.value)
}

const handleClose = () => {
  if (props.isSubmitting) return

  emit('close')
}

watch(
  () => props.open,
  (open) => {
    if (open) {
      step.value = 'select'
      selectedMethod.value = 'qr'
    }
  },
)
</script>

<template>
  <Teleport to="body">
    <div
      v-if="open"
      class="fixed inset-0 z-[100] grid place-items-center bg-slate-950/55 px-4 py-6 backdrop-blur-sm"
      @click.self="handleClose"
    >
      <section class="animate-pop w-full max-w-md overflow-hidden rounded-3xl bg-white shadow-[0_30px_90px_rgba(15,31,77,0.35)]">
        <div class="hero-gradient px-6 py-5 text-white">
          <div class="flex items-start justify-between gap-4">
            <div>
              <p class="text-xs font-black uppercase tracking-wide text-[#f5a400]">
                Secure checkout
              </p>
              <h2 class="mt-2 text-2xl font-black">
                {{ step === 'success' ? 'ຊຳລະເງິນສຳເລັດ' : 'ຊຳລະເງິນ' }}
              </h2>
              <p class="mt-1 line-clamp-1 text-sm text-white/70">{{ courseTitle }}</p>
            </div>

            <button
              type="button"
              class="grid h-9 w-9 place-items-center rounded-full bg-white/10 text-lg font-black text-white transition hover:bg-white/20"
              :disabled="isSubmitting"
              @click="handleClose"
            >
              ×
            </button>
          </div>
        </div>

        <div class="p-6">
          <div v-if="step === 'select'" class="space-y-5">
            <div class="rounded-2xl bg-slate-50 p-4">
              <div class="flex items-center justify-between">
                <span class="text-sm font-bold text-slate-500">ລາຄາຄອສ</span>
                <span class="font-number text-2xl font-black text-[#f5a400]">
                  {{ formatMoney(numericPrice) }}
                </span>
              </div>

              <div class="mt-3 space-y-1 border-t border-slate-200 pt-3 text-xs font-bold text-slate-500">
                <div class="flex justify-between">
                  <span>ຄ່າລະບົບ 20%</span>
                  <span>{{ formatMoney(commission) }}</span>
                </div>
                <div class="flex justify-between text-emerald-600">
                  <span>ຜູ້ສອນໄດ້ຮັບ</span>
                  <span>{{ formatMoney(teacherEarning) }}</span>
                </div>
              </div>
            </div>

            <div class="space-y-2">
              <p class="text-sm font-black text-[#0f1f4d]">ເລືອກວິທີຊຳລະ</p>

              <button
                v-for="method in methods"
                :key="method.id"
                type="button"
                class="flex w-full items-center gap-3 rounded-2xl border border-slate-200 p-3 text-left transition hover:border-[#f5a400] hover:bg-[#f5a400]/5"
                @click="handlePay(method.id)"
              >
                <span class="grid h-11 w-11 place-items-center rounded-xl bg-[#f5a400]/10 text-xl font-black text-[#f5a400]">
                  {{ method.icon }}
                </span>
                <span class="flex-1">
                  <span class="block text-sm font-black text-[#0f1f4d]">{{ method.label }}</span>
                  <span class="block text-xs font-bold text-slate-500">{{ method.desc }}</span>
                </span>
                <span class="text-lg font-black text-slate-300">›</span>
              </button>
            </div>
          </div>

          <div v-else-if="step === 'processing'" class="py-7 text-center">
            <div
              v-if="selectedMethod === 'qr'"
              class="mx-auto grid h-48 w-48 grid-cols-7 gap-1 rounded-2xl bg-slate-950 p-5"
            >
              <span
                v-for="index in 49"
                :key="index"
                class="rounded-[3px]"
                :class="index % 3 === 0 || index % 5 === 0 || index < 9 ? 'bg-white' : 'bg-slate-950'"
              ></span>
            </div>

            <div
              v-else
              class="mx-auto grid h-24 w-24 place-items-center rounded-full bg-[#f5a400]/15 text-4xl text-[#f5a400]"
            >
              {{ selectedMethod === 'card' ? '▭' : '▣' }}
            </div>

            <div class="mx-auto mt-6 h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-[#f5a400]"></div>
            <p class="mt-4 text-sm font-bold text-slate-500">
              ກຳລັງກວດສອບການຊຳລະ...
            </p>
          </div>

          <div v-else class="py-7 text-center">
            <div class="mx-auto grid h-20 w-20 place-items-center rounded-full bg-emerald-50 text-4xl text-emerald-600">
              ✓
            </div>
            <h3 class="mt-5 text-xl font-black text-[#0f1f4d]">ສ້າງ payment ສຳເລັດ</h3>
            <p class="mx-auto mt-2 max-w-xs text-sm leading-6 text-slate-500">
              ລາຍການຊຳລະຈະຢູ່ສະຖານະ pending ເພື່ອໃຫ້ admin ກວດສອບ
            </p>

            <button
              type="button"
              :disabled="isSubmitting"
              class="mt-6 w-full rounded-2xl bg-[#142b63] px-5 py-4 text-sm font-black text-white transition hover:bg-[#0e214d] disabled:cursor-not-allowed disabled:bg-slate-400"
              @click="handleSuccess"
            >
              {{ isSubmitting ? 'ກຳລັງບັນທຶກ...' : 'ຢືນຢັນການຊຳລະ' }}
            </button>
          </div>
        </div>
      </section>
    </div>
  </Teleport>
</template>

// .codex_tmp/edu-forge-reference/edu-forge-nexus-main/src/components/PaymentDialog.tsx
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CheckCircle, CreditCard, QrCode, Smartphone, Loader2 } from "lucide-react";

interface PaymentDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  courseTitle: string;
  price: number;
  onPaymentSuccess: (method: string) => void;
}

const METHODS = [
  { id: "qr", label: "QR Code / PromptPay", icon: QrCode, desc: "ສະແກນ QR ຊຳລະ" },
  { id: "card", label: "ບັດເຄຣດິດ / ເດບິດ", icon: CreditCard, desc: "Visa, Mastercard" },
  { id: "mobile", label: "Mobile Banking", icon: Smartphone, desc: "BCEL One, JDB" },
];

const PaymentDialog = ({ open, onOpenChange, courseTitle, price, onPaymentSuccess }: PaymentDialogProps) => {
  const [step, setStep] = useState<"select" | "processing" | "success">("select");
  const [selectedMethod, setSelectedMethod] = useState("");

  const handlePay = (method: string) => {
    setSelectedMethod(method);
    setStep("processing");
    // Simulate payment processing
    setTimeout(() => {
      setStep("success");
    }, 2000);
  };

  const handleClose = () => {
    if (step === "success") {
      onPaymentSuccess(selectedMethod);
    }
    setStep("select");
    setSelectedMethod("");
    onOpenChange(false);
  };

  const commissionRate = 0.2;
  const commission = price * commissionRate;
  const teacherEarning = price - commission;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="font-heading">
            {step === "success" ? "ຊຳລະເງິນສຳເລັດ!" : "ຊຳລະເງິນ"}
          </DialogTitle>
          <DialogDescription>{courseTitle}</DialogDescription>
        </DialogHeader>

        <AnimatePresence mode="wait">
          {step === "select" && (
            <motion.div
              key="select"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-4"
            >
              {/* Price summary */}
              <div className="rounded-lg bg-muted/50 p-4 space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">ລາຄາຄອສ</span>
                  <span className="font-bold text-lg text-secondary">₭{price.toLocaleString()}</span>
                </div>
                <div className="border-t pt-2 space-y-1 text-xs text-muted-foreground">
                  <div className="flex justify-between">
                    <span>ຄ່າຄອມມິດຊັ່ນລະບົບ (20%)</span>
                    <span>₭{commission.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>ຜູ້ສອນໄດ້ຮັບ</span>
                    <span className="text-accent font-medium">₭{teacherEarning.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Payment methods */}
              <div className="space-y-2">
                <p className="text-sm font-medium">ເລືອກວິທີຊຳລະ:</p>
                {METHODS.map((m) => (
                  <button
                    key={m.id}
                    onClick={() => handlePay(m.id)}
                    className="w-full flex items-center gap-3 p-3 rounded-lg border hover:bg-muted/50 hover:border-secondary transition-all text-left"
                  >
                    <div className="h-10 w-10 rounded-lg bg-secondary/10 flex items-center justify-center">
                      <m.icon className="h-5 w-5 text-secondary" />
                    </div>
                    <div className="flex-1">
                      <div className="text-sm font-medium">{m.label}</div>
                      <div className="text-xs text-muted-foreground">{m.desc}</div>
                    </div>
                  </button>
                ))}
              </div>
            </motion.div>
          )}

          {step === "processing" && (
            <motion.div
              key="processing"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="py-12 text-center space-y-4"
            >
              {selectedMethod === "qr" ? (
                <>
                  {/* Mock QR Code */}
                  <div className="mx-auto w-48 h-48 bg-foreground rounded-xl flex items-center justify-center">
                    <div className="grid grid-cols-5 gap-1 p-4">
                      {Array.from({ length: 25 }).map((_, i) => (
                        <div
                          key={i}
                          className={`w-5 h-5 rounded-sm ${Math.random() > 0.4 ? "bg-background" : "bg-foreground"}`}
                        />
                      ))}
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground">ສະແກນ QR Code ເພື່ອຊຳລະ</p>
                  <div className="flex items-center justify-center gap-2 text-secondary">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span className="text-sm">ກຳລັງລໍຖ້າການຊຳລະ...</span>
                  </div>
                </>
              ) : (
                <>
                  <Loader2 className="h-12 w-12 mx-auto text-secondary animate-spin" />
                  <p className="text-sm text-muted-foreground">ກຳລັງດຳເນີນການ...</p>
                </>
              )}
            </motion.div>
          )}

          {step === "success" && (
            <motion.div
              key="success"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="py-8 text-center space-y-4"
            >
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ type: "spring", stiffness: 200 }}
                className="mx-auto h-16 w-16 rounded-full bg-accent/20 flex items-center justify-center"
              >
                <CheckCircle className="h-10 w-10 text-accent" />
              </motion.div>
              <h3 className="font-heading font-bold text-lg">ຊຳລະເງິນສຳເລັດ!</h3>
              <p className="text-sm text-muted-foreground">
                ທ່ານສາມາດເຂົ້າຮຽນຄອສ "{courseTitle}" ໄດ້ແລ້ວ
              </p>
              <div className="text-xs text-muted-foreground space-y-1">
                <p>ຈຳນວນ: <strong className="text-foreground">₭{price.toLocaleString()}</strong></p>
                <p>ວິທີ: <Badge variant="outline" className="text-xs">{METHODS.find((m) => m.id === selectedMethod)?.label}</Badge></p>
              </div>
              <Button onClick={handleClose} className="mt-4">
                ເລີ່ມຮຽນເລີຍ!
              </Button>
            </motion.div>
          )}
        </AnimatePresence>
      </DialogContent>
    </Dialog>
  );
};

export default PaymentDialog;
